---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
        lock_timeout: 300
        force_apt_get: yes
