---
- hosts: all
  become: yes
  tasks:
    - name: Obtain MAC address of ens3
      shell: "ip link show ens3 | grep link/ether | awk '{print $2}'"
      register: mac_address
      changed_when: false

    - name: Extract the last 4 characters from the MAC address (excluding colon)
      set_fact:
        last_four_chars: "{{ mac_address.stdout.replace(':', '')[-4:] }}"

    - name: Print the last four characters for debugging
      debug:
        msg: "Last four characters of MAC without colons: {{ last_four_chars }}"

    - name: Set the hostname using command
      command:
        cmd: "hostnamectl set-hostname jamesscottworker-{{ last_four_chars }}"
      when: ansible_hostname != "jamesscottworker-{{ last_four_chars }}"
      notify: Restart Network Service


  handlers:
    - name: Restart Network Service
      service:
        name: network
        state: restarted
