---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Obtain MAC address of ens3
      shell: "/usr/sbin/ip link show ens3 | /bin/grep link/ether | /usr/bin/awk '{print $2}'"
      register: mac_address
      changed_when: false

    - name: Extract the last 4 characters from the MAC address (excluding colon)
      set_fact:
        last_four_chars: "{{ mac_address.stdout.replace(':', '')[-4:] }}"

    - name: Print the last four characters for debugging
      debug:
        msg: "Last four characters of MAC without colons: {{ last_four_chars }}"

    - name: Set the hostname using alternative method
      shell: "echo \"jamesscottworker-{{ last_four_chars }}\" | sudo tee /etc/hostname && sudo /bin/hostname -F /etc/hostname"
      when: ansible_hostname != "jamesscottworker-" + last_four_chars
      notify: Restart Network Service

    handlers:
        - name: Restart Network Service
          service:
            name: networking  # for Ubuntu
            # name: NetworkManager  # for CentOS/Fedora
            state: restarted

