---
- hosts: all
  become: true
  tasks:

    # Remove all Docker containers
    - name: Remove all Docker containers
      command: docker rm -f $(docker ps -a -q)
      ignore_errors: yes

    # Stop kubevip service if it exists
    - name: Stop kubevip service
      systemd:
        name: kubevip
        state: stopped
      ignore_errors: yes

    # Uninstall kubevip if installed
    - name: Uninstall kubevip
      command: kubevip uninstall
      ignore_errors: yes

    # Uninstall Docker
    - name: Uninstall Docker packages
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent
      ignore_errors: yes

    - name: Remove Docker repositories
      command: rm -f /etc/apt/sources.list.d/docker.list
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove all unused packages
      command: apt-get autoremove -y
      ignore_errors: yes

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/docker
      ignore_errors: yes
