---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "$tillg02"
  tasks:
    - name: Ensure the ubuntu user has passwordless sudo access
      lineinfile:
        path: /etc/sudoers.d/90-ansible-ubuntu
        create: yes
        regexp: '^ubuntu ALL='
        line: 'ubuntu ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        state: present
