---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create /etc/sudoers.d/ubuntu file
      file:
        path: /etc/sudoers.d/ubuntu
        state: touch

    - name: Add the ubuntu user with passwordless sudo access in the file
      lineinfile:
        path: /etc/sudoers.d/ubuntu
        create: yes
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        state: present

    - name: Set correct permissions on the file
      file:
        path: /etc/sudoers.d/ubuntu
        mode: '0440'
