---
- name: Ensure 'ubuntu' user has password-less sudo access
  hosts: all
  become: yes
  tasks:
        - name: Give sudo access to ubuntu user
          blockinfile:
            path: /etc/sudoers.d/ubuntu
            create: yes
            block: |
              # Gives sudo access to the ubuntu user
              ubuntu ALL=(ALL) NOPASSWD: ALL
        
