---
- name: Ensure 'ubuntu' user has password-less sudo access
  hosts: all
  become: yes
  tasks:
    - name: Give sudo access to ubuntu user
      blockinfile:
        path: /etc/sudoers
        insertafter: 'root    ALL=(ALL)       ALL'
        block: |
          # Gives sudo access to the ubuntu user
          ubuntu        ALL=(ALL)       NOPASSWD: ALL
