---
- name: Ensure 'ubuntu' user has password-less sudo access
  hosts: all
  become: yes
  tasks:
    - name: Give sudo access to ubuntu user
      blockinfile:
        path: /etc/sudoers.d/ubuntu
        create: yes
        block: |
          # Gives sudo access to the ubuntu user
          ubuntu ALL=(ALL) NOPASSWD: ALL
      validate: 'visudo -cf %s'
      become_method: sudo

    - name: Ensure correct permissions on sudoers file
      file:
        path: /etc/sudoers.d/ubuntu
        mode: '0440'
      become_method: sudo

