---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:

    - name: Ensure APT lock is absent
      file:
        path: /var/lib/apt/lists/lock
        state: absent
    - name: Check current user and sudo capabilities
      command: whoami && sudo -l
      register: debug_output

    - name: Display debug output
      debug:
        var: debug_output.stdout_lines

    - name: update apt packages
      apt:
        update_cache: yes
      become: true
      become_method: sudo
      register: result
    - name: Check current user and sudo capabilities
      command: whoami && sudo -l
      register: debug_output

    - name: Display debug output
      debug:
        var: debug_output.stdout_lines

    
    
    
    - name: update apt packages
      apt:
        update_cache: yes
      register: result

    - name: install curl
      apt:
        name: curl
        state: present

    - name: upgrade all apt packages
      apt:
        upgrade: 'yes'
      register: result

    - name: check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: print message if reboot is required
      debug:
        msg: "System reboot is required"
      when: reboot_required.stat.exists

    - name: print message if reboot is not required
      debug:
        msg: "System reboot is not required"
      when: not reboot_required.stat.exists

    - name: print update result
      debug:
        msg: "APT result: {{ result }}"
