---
- hosts: all
  become: true
  tasks:
    - name: Get IP address
      debug:
        msg: "IP Address: {{ ansible_default_ipv4['address'] }}"

    - name: Get hostname
      command: hostname
      register: hostname

    - name: Print hostname
      debug:
        msg: "Hostname: {{ hostname.stdout }}"

    - name: Get disk space
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space

    - name: Print disk space
      debug:
        msg: "Remaining Disk Space: {{ disk_space.stdout }}"
