---
- name: install microk8s
  hosts: all
  become: yes
  tasks:
    - name: install microk8s
      snap:
        name: microk8s
        classic: yes

    - name: add user permissions
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes
