---
- hosts: all
  become: true
  tasks:
    - name: Check if /opt/ansible directory exists
      stat: 
        path: /opt/ansible
      register: dir_status
      
    - name: Create /opt/ansible directory if it does not exist
      file:
        path: /opt/ansible
        state: directory
        mode: '0755'
      when: not dir_status.stat.exists
      
    - name: Check Docker status
      shell: docker -v || true
      register: docker_status
      ignore_errors: true

    - name: Install Docker
      shell: curl -sSL https://get.docker.com/ | sh
      when: docker_status.rc != 0

    - name: Check Docker Compose status
      shell: docker-compose -v || true
      register: docker_compose_status
      ignore_errors: true

    - name: Install Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      when: docker_compose_status.rc != 0

    - name: Create docker-compose.yaml
      copy:
        dest: "/opt/ansible/docker-compose.yaml"
        content: |
          version: '3.1'
          services:
            portainer:
              image: portainer/portainer
              restart: always
              ports:
                - 9000:9000
                - 8000:8000
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - portainer_data:/data
          volumes:
            portainer_data:
