---
- hosts: all
  become: true
  tasks:
    - name: Ensure dpkg is in a consistent state
      ansible.builtin.command:
        cmd: dpkg --configure -a
      ignore_errors: yes

    - name: Uninstall all conflicting packages
      ansible.builtin.command:
        cmd: apt-get remove -y {{ item }}
      loop:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc
      ignore_errors: yes

    - name: Install necessary packages
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
...
