---
- hosts: all
  become: true
  tasks:
    - name: Uninstall all conflicting packages
      ansible.builtin.command:
        cmd: apt-get remove -y {{ item }}
      loop:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install APT dependencies
      apt:
        name: ['ca-certificates', 'curl', 'gnupg']
        state: present

    - name: Create /etc/apt/keyrings directory if it does not exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.shell: 
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        warn: no

    - name: Give read access to all users for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Ensure coreutils is installed
      apt:
        name: coreutils
        state: present

    - name: Set up the Docker stable repository
      ansible.builtin.shell:
        cmd: >
          echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        warn: no

    - name: Update APT package cache again
      apt:
        update_cache: yes

    - name: Install Docker Engine, Docker CE CLI, containerd.io, Docker Buildx and Docker Compose
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
        state: present

    - name: Verify Docker Engine installation by running the hello-world image
      docker_container:
        name: hello-world-test
        image: hello-world
        state: started
        restart_policy: never
        cleanup: true
...
