---
- hosts: 192.168.12.44
  become: yes
  tasks:
    - name: Fix broken dependencies
      command: apt --fix-broken install -y
      become: yes

    - name: Update all system package
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all system package
      apt:
        upgrade: dist
        update_cache: yes

    - name: Ensure dpkg is in a consistent state
      command: dpkg --configure -a
      become: yes

    - name: Uninstall all conflicting packages
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    # You can continue here with the rest of your tasks
...


    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's official apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
...
