---
- hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure old versions of Docker are not installed
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-engine
        - docker.io
        - containerd runc

    - name: Setup Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker CE and dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Check if Docker is running
      systemd:
        state: started
        enabled: yes
        name: docker

    - name: Run Rancher container
      docker_container:
        name: rancher
        image: rancher/rancher:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "80:80"
          - "443:443"

    - name: Install RKE
      get_url:
        url: "https://github.com/rancher/rke/releases/download/v1.2.6/rke_linux-amd64"
        dest: "/usr/local/bin/rke"
        mode: "u+x,g+x"

    - name: Create a directory for the Kubernetes configuration
      file:
        path: /etc/rancher/
        state: directory

    - name: Create Kubernetes configuration file
      copy:
        dest: /etc/rancher/cluster.yml
        content: |
          ---
          nodes:
          - address: localhost
            user: root
            role:
            - controlplane
            - etcd
            - worker

    - name: Stand up Kubernetes cluster
      command: 
        cmd: rke up --config /etc/rancher/cluster.yml
