---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Ensure the ubuntu user has passwordless sudo access
      copy:
        dest: /etc/sudoers.d/ubuntu
        content: "ubuntu ALL=(ALL:ALL) NOPASSWD:ALL\n"
        mode: '0440'
        validate: 'visudo -cf %s'
