---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Check the user
      command: whoami
      register: result
    
    - debug:
        var: result.stdout
    
    - name: Ensure user "ubuntu" can run all commands as root without a password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ubuntu
        content: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
