---
- hosts: all
  become: true
  tasks:
    - name: Ensure user "ubuntu" can run all commands as root without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ubuntu ALL'
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
...
