---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Ensure the ubuntu user has passwordless sudo access
      lineinfile:
        dest: /etc/sudoers
        regexp: '^ubuntu ALL='
        line: 'ubuntu ALL=(ALL:ALL) NOPASSWD:ALL'
        state: present
