---
- hosts: all
  become: true
  vars:
    username: ubuntu
  tasks:
    - name: Change owner and permissions for /opt/ansible/worker2 and its subdirectories
      file:
        path: "{{ item }}"
        owner: "{{ username }}"
        mode: '0777'
        recurse: true
      with_fileglob:
        - /opt/ansible/worker2/*
