---
- hosts: all
  become: true
  tasks:

    - name: Purge current NVIDIA drivers
      apt:
        name: "nvidia-*"
        state: absent
        purge: yes

    - name: Add NVIDIA PPA
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        state: present
      register: ppa_added

    - name: Update system packages
      apt:
        update_cache: yes
      when: ppa_added.changed

    - name: Install NVIDIA driver version 470
      apt:
        name: nvidia-driver-470
        state: present

    - name: Reboot the machine
      reboot:

    - name: Check NVIDIA driver version
      command: nvidia-smi
      register: nvidia_version
      changed_when: false

    - name: Print NVIDIA driver version
      debug:
        var: nvidia_version.stdout_lines

    - name: Add Nvidia Docker GPG key
      shell: curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -

    - name: Add Nvidia Docker repo
      shell: |
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

    - name: Update and install nvidia-docker2
      shell: |
        sudo apt-get update
        sudo apt-get install -y nvidia-docker2

    - name: Restart Docker
      shell: sudo pkill -SIGHUP dockerd

    - name: Final Reboot
      reboot:
