---
- hosts: all
  become: true
  tasks:

    - name: Purge current NVIDIA drivers
      apt:
        name: "nvidia-*"
        state: absent
        purge: yes

    - name: Add NVIDIA PPA
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        state: present
      register: ppa_added

    - name: Update system packages
      apt:
        update_cache: yes
      when: ppa_added.changed

    - name: Install NVIDIA driver version 470
      apt:
        name: nvidia-driver-470
        state: present

    - name: Reboot the machine
      reboot:

    - name: Check NVIDIA driver version
      command: nvidia-smi
      register: nvidia_version
      changed_when: false

    - name: Print NVIDIA driver version
      debug:
        var: nvidia_version.stdout_lines
