---
- hosts: all
  become: true
  tasks:
    - name: Pull the latest Docker Compose images
      command: docker compose pull -f /opt/ansible/plex/docker-compose.yaml

    - name: Start Docker Compose
      command: docker compose up -d -f /opt/ansible/plex/docker-compose.yaml

    - name: Remove all unused Docker images
      command: docker image prune -af
      register: image_prune
      changed_when: "'Total reclaimed space:' in image_prune.stdout"

    - name: Remove all unused Docker volumes
      command: docker volume prune -f
      register: volume_prune
      changed_when: "'Total reclaimed space:' in volume_prune.stdout"
