---
- hosts: all
  become: true
  tasks:
    - name: Gather facts
      setup:
        filter: ansible_mounts

    - name: Display disk usage
      debug:
        msg: "Host: {{ ansible_facts['nodename'] }}, Disk: {{ item.device }}, Mount: {{ item.mount }}, Used: {{ ((item.size_total - item.size_available) / 1024 / 1024 / 1024) | round(2) }} GB, Free: {{ (item.size_available / 1024 / 1024 / 1024) | round(2) }} GB, Total: {{ (item.size_total / 1024 / 1024 / 1024) | round(2) }} GB"
      loop: "{{ ansible_mounts }}"
