---
- hosts: all
  become: true
  vars:
    base_url: 'http://192.168.12.190:8080/sabnzbd/api'
    api_key: 'b5078b24a8794870b632b3e9f17a2b84'
  tasks:
    - name: Resume queue
      uri:
        url: "{{ base_url }}?mode=resume&apikey={{ api_key }}&output=json"
        method: GET
