---
- hosts: all
  become: true
  vars:
    username: ubuntu
    password: Stillg02
  tasks:
    - name: Check if /opt/ansible directory exists
      stat: 
        path: /opt/ansible
      register: dir_status
      
    - name: Create /opt/ansible directory if it does not exist
      file:
        path: /opt/ansible
        state: directory
        mode: '0755'
      when: not dir_status.stat.exists
      
    - name: Check if /opt/ansible/webtop_data directory exists
      stat: 
        path: /opt/ansible/webtop_data
      register: webtop_data_dir_status
      
    - name: Create /opt/ansible/webtop_data directory if it does not exist
      file:
        path: /opt/ansible/webtop_data
        state: directory
        mode: '0755'
      when: not webtop_data_dir_status.stat.exists
      
    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add '{{ username }}' user to Docker group
      user:
        name: '{{ username }}'
        groups: docker
        append: yes
      
    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
      when: "'docker' in ansible_local"

    - name: Create .env file
      copy:
        dest: "/opt/ansible/.env"
        content: |
          PASSWORD=Stillg02

    - name: Create docker-compose.yaml
      copy:
        dest: "/opt/ansible/docker-compose.yaml"
        content: |
          version: '3.1'
          services:
            webtop:
              image: ghcr.io/linuxserver/webtop:ubuntu-mate #choose your flavor
              container_name: webtop
              #privileged: true #optional but not needed unless you are running kde or i3 or other tools
              environment:
                - PUID=1000 # based on id
                - PGID=1000 # based on group
                - TZ=Pacific/Auckland # your timezone
              volumes:
                - /home/user/webtop/config:/config #home directory
                #- /var/run/docker.sock:/var/run/docker.sock #optional only if you need access to docker winthin this container
              ports:
                - 4000:3000
              shm_size: "4gb" #optional but set to 1GB or higher to prevent browser crashes
              restart: unless-stopped
              env_file:  #only necessary if you want to change the password, see .env file
                 - .env

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Start Docker Compose
      shell: cd /opt/ansible && docker compose up -d
