---
- hosts: all
  become: yes
  tasks:
    - name: Ensure user 'ubuntu' exists
      user:
        name: ubuntu
        groups: sudo
        append: yes

    - name: Allow 'ubuntu' to run sudo commands without password
      lineinfile:
        path: /etc/sudoers.d/ubuntu_ansible
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        create: yes
        validate: 'visudo -cf %s'
