---
- name: Install and Configure MicroK8s and MicroCeph
  hosts: all
  become: yes
  vars:
    ansible_user: ubuntu
  tasks:
    - name: Install MicroK8s from the Snap Store
      command: snap install microk8s --channel=1.28/stable --classic
      args:
        timeout: 120 # timeout in seconds

    - name: Install MicroCeph from the Snap Store
      command: snap install microceph --channel=latest/edge
      args:
        timeout: 120 # timeout in seconds

    - name: Create .kube directory
      become: no
      file:
        path: "~/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Change ownership of the .kube directory
      file:
        path: "~/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Add the user to the microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    # Using shell module instead of command, to bypass the potential issues with newgrp
    - name: Apply new group to the current session
      shell: newgrp microk8s
      become: no
      args:
        executable: /bin/bash
        timeout: 60 # timeout in seconds
