---
- hosts: all
  become: yes
  vars:
    hostname_prefix: "jamesscott-kube"  # Update this as per your requirements

  tasks:
    - name: Obtain MAC address of enp1s0
      shell: "/usr/sbin/ip link show enp1s0 | /bin/grep link/ether | /usr/bin/awk '{print $2}'"
      register: mac_address
      changed_when: false

    - name: Check if MAC address was fetched successfully
      fail:
        msg: "Failed to obtain MAC address."
      when: mac_address.stdout is none or mac_address.stdout == ""

    - name: Extract the last 4 characters from the MAC address (excluding colon)
      set_fact:
        last_four_chars: "{{ mac_address.stdout.replace(':', '')[-4:] }}"

    - name: Check if last_four_chars was extracted successfully
      fail:
        msg: "Failed to extract the last four characters from the MAC address."
      when: last_four_chars is none or last_four_chars == ""

    - name: Print the last four characters for debugging
      debug:
        msg: "Last four characters of MAC without colons: {{ last_four_chars }}"

    - name: Set the hostname
      shell: "echo \"{{ hostname_prefix }}-{{ last_four_chars }}\" | sudo tee /etc/hostname && sudo /bin/hostname -F /etc/hostname"
      when: ansible_hostname != (hostname_prefix ~ "-" ~ last_four_chars)
      async: 10  # allow max 10 seconds for the command to complete
      poll: 5    # check every 5 seconds if the command has completed

    # This task updates the /etc/hosts file with the new hostname
    - name: Update /etc/hosts with new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1 {{ hostname_prefix }}-{{ last_four_chars }}"
      when: ansible_hostname != (hostname_prefix ~ "-" ~ last_four_chars)
