---
- hosts: all
  become: yes
  tasks:
    - name: Ensure ubuntu user has passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
