---
- hosts: all
  become: true
  tasks:
    - name: Check available disk space
      shell: df --output=avail -BG /mnt/SSD-NFS/sabnzb/Downloads/complete | tail -n 1 | tr -d '[:space:]'
      register: disk_space
      changed_when: false

    - name: Convert available disk space to integer
      set_fact:
        available_space: "{{ disk_space.stdout | regex_replace('G', '') | int }}"

    - name: Delete all files in the directory if available space is less than 10GB
      shell: rm -rf /mnt/SSD-NFS/sabnzb/Downloads/complete/*
      when: available_space < 10
