---
- hosts: all
  tasks:
    - name: Get disk space
      become: true
      shell: df -h
      register: disk_space

    - name: Display disk space
      debug:
        var: disk_space.stdout_lines
