- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Docker compose pull
      command: docker compose -f /opt/home-stack-23/docker-compose.yml pull
      become: yes
      become_method: sudo

    - name: Docker compose up -d
      command: docker compose -f /opt/home-stack-23/docker-compose.yml up -d
      become: yes
      become_method: sudo
