---
- hosts: all
  become: true
  tasks:
    - name: Create new user named ansible
      user:
        name: ansible
        shell: /bin/bash
        create_home: yes

    - name: Ensure .ssh directory exists for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Add authorized key for ansible user
      authorized_key:
        user: ansible
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2E...gs4162@HC-NZ-LT97"

    - name: Grant ansible user password-less sudo privileges
      lineinfile:
        dest: /etc/sudoers.d/ansible
        state: present
        create: yes
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set appropriate permissions for ansible sudoers file
      file:
        path: /etc/sudoers.d/ansible
        mode: '0440'
        owner: root
        group: root
