---
- hosts: all
  become: true
  tasks:
    - name: Ensure .ssh directory exists for ubuntu user
      file:
        path: /home/ubuntu/.ssh
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Fetch authorized_keys from the provided URL
      get_url:
        url: "https://raw.githubusercontent.com/gs4162/ansible/master/playbooks/edge-workers/extra/authorized_keys"
        dest: "/home/ubuntu/.ssh/authorized_keys_tmp"
        mode: '0600'
        owner: ubuntu
        group: ubuntu

    - name: Set fetched authorized_keys as authorized keys for ubuntu user
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/authorized_keys_tmp') }}"
        path: "/home/ubuntu/.ssh/authorized_keys"

    - name: Remove temporary authorized_keys_tmp
      file:
        path: "/home/ubuntu/.ssh/authorized_keys_tmp"
        state: absent

    - name: Grant ubuntu user password-less sudo privileges
      lineinfile:
        dest: /etc/sudoers.d/ubuntu
        state: present
        create: yes
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set appropriate permissions for ubuntu sudoers file
      file:
        path: /etc/sudoers.d/ubuntu
        mode: '0440'
        owner: root
        group: root
